export const japanStationToJapanese: Record<string, string> = {
  "Tokyo": "東京",
  "Shinagawa": "品川",
  "Shinjuku": "新宿",
  "Shibuya": "渋谷",
  "Ikebukuro": "池袋",
  "Ueno": "上野",
  "Akihabara": "秋葉原",
  "Shin-Yokohama": "新横浜",
  "Yokohama": "横浜",
  "Omiya": "大宮",
  "Nagoya": "名古屋",
  "Kyoto": "京都",
  "Shin-Osaka": "新大阪",
  "Osaka": "大阪",
  "Kobe": "神戸",
  "Shin-Kobe": "新神戸",
  "Himeji": "姫路",
  "Okayama": "岡山",
  "Hiroshima": "広島",
  "Hakata": "博多",
  "Kumamoto": "熊本",
  "Kagoshima-Chuo": "鹿児島中央",
  "Sendai": "仙台",
  "Morioka": "盛岡",
  "Shin-Aomori": "新青森",
  "Shin-Hakodate-Hokuto": "新函館北斗",
  "Sapporo": "札幌",
  "Kanazawa": "金沢",
  "Toyama": "富山",
  "Nagano": "長野",
  "Niigata": "新潟",
  "Fukuoka": "福岡",
};

export const koreaStationToKorean: Record<string, string> = {
  "Seoul (SNC)": "서울",
  "Yongsan": "용산",
  "Yeongdeungpo": "영등포",
  "Cheongnyangni": "청량리",
  "Gwangmyeong": "광명",
  "Suwon": "수원",
  "Cheonan-Asan": "천안아산",
  "Osong": "오송",
  "Daejeon": "대전",
  "Seodaejeon": "서대전",
  "Dongdaegu": "동대구",
  "Daegu": "대구",
  "Singyeongju": "신경주",
  "Ulsan": "울산",
  "Busan (BSN)": "부산",
  "Pohang": "포항",
  "Masan": "마산",
  "Jinju": "진주",
  "Iksan": "익산",
  "Jeonju": "전주",
  "Gwangju-Songjeong": "광주송정",
  "Mokpo": "목포",
  "Yeosu-EXPO": "여수EXPO",
  "Gangneung": "강릉",
  "Donghae": "동해",
  "Pyeongchang": "평창",
};
